"""All models

Revision ID: ab097eacba6c
Revises: 2bbe97b6abf2
Create Date: 2025-01-12 13:26:41.984979+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab097eacba6c"
down_revision: Union[str, None] = "2bbe97b6abf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("profile_email_key", "profile", type_="unique")
    op.create_index(op.f("ix_profile_email"), "profile", ["email"], unique=True)
    op.create_index(op.f("ix_profile_id"), "profile", ["id"], unique=False)
    op.create_index(op.f("ix_review_id"), "review", ["id"], unique=False)
    op.create_index(op.f("ix_skill_id"), "skill", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skill_id"), table_name="skill")
    op.drop_index(op.f("ix_review_id"), table_name="review")
    op.drop_index(op.f("ix_profile_id"), table_name="profile")
    op.drop_index(op.f("ix_profile_email"), table_name="profile")
    op.create_unique_constraint("profile_email_key", "profile", ["email"])
    # ### end Alembic commands ###
