"""generate initial migration

Revision ID: 7a72b9c2a55c
Revises: 1edc084998fe
Create Date: 2023-09-26 11:29:32.529046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a72b9c2a55c"
down_revision: Union[str, None] = "1edc084998fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("skill", sa.Column("name", sa.String(), nullable=False))
    op.drop_constraint("skill_skill_name_key", "skill", type_="unique")
    op.create_unique_constraint(None, "skill", ["name"])
    op.drop_column("skill", "skill_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "skill",
        sa.Column("skill_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "skill", type_="unique")
    op.create_unique_constraint("skill_skill_name_key", "skill", ["skill_name"])
    op.drop_column("skill", "name")
    # ### end Alembic commands ###
